#!/bin/bash

ARGS="rear_detector_distance_m=4.099 gen_rear_detector_distance_m=4.099 analysis_rear_bank_pixel_number=512 with_beamstop=False larmor_2022_experiment=True gen_larmor_2022_experiment=True rear_detector_only=True event_gen=flood x_offset_meters=0.005"
ess_lokisim_bcsbanks_sim $ARGS -lESS_Empty |grep '^G4Launcher::Launcher'
if [ ${PIPESTATUS[0]} == 0 ]; then
    ess_lokiana_rear_bank_larmor lokisim.griff
else
    exit 1
fi