#!/bin/bash

ARGS="rear_detector_distance_m=10 gen_rear_detector_distance_m=10  aiming_straw_pixel_number=32 analysis_straw_pixel_number=64 with_beamstop=False event_gen=masking"
ess_lokisim_bcsbanks_sim $ARGS -lESS_Empty |grep '^G4Launcher::Launcher'
if [ ${PIPESTATUS[0]} == 0 ]; then
    ess_lokiana_loki_ana_masking lokisim.griff
else
    exit 1
fi

ARGS="rear_detector_distance_m=4.099 gen_rear_detector_distance_m=4.099  aiming_straw_pixel_number=1024 analysis_straw_pixel_number=512 rear_detector_only=True with_beamstop=False larmor_2022_experiment=True gen_larmor_2022_experiment=True event_gen=masking x_offset_meters=0.005" 
ess_lokisim_bcsbanks_sim $ARGS -lESS_Empty |grep '^G4Launcher::Launcher'
if [ ${PIPESTATUS[0]} == 0 ]; then
    ess_lokiana_loki_ana_masking lokisim.griff
else
    exit 1
fi