#!/bin/bash

ARGS="det_only=true"
ess_lokisim_larmor_sim $ARGS -lESS_Empty |egrep '^G4Launcher::Launcher|NXS'
if [ ${PIPESTATUS[0]} == 0 ]; then
    ess_lokiana_larmor_det_mcpl larmor_CountingGas_Converter.griff
else
    exit 1
fi
