#!/bin/bash

ARGS="rear_detector_distance_m=4.099 rear_bank_pixel_number=512 rear_detector_only=True with_beamstop=False larmor_rear_bank_experiment=True event_gen=flood x_offset_meters=0.005"
ess_lokisim_bcsbanks_sim $ARGS -lESS_Empty |egrep '^G4Launcher::Launcher|NXS'
if [ ${PIPESTATUS[0]} == 0 ]; then
    ess_lokiana_rear_bank_larmor lokisim.griff
else
    exit 1
fi