#!/usr/bin/env python3
import G4GeoLoki.LokiMaskingHelper as Mask

aimHelper = Mask.MaskingHelper(4.099 * 1000) #[mm]
pixelFile = open("pixelFile_oldNumbering.txt", "w")

numberOfPixels = aimHelper.getTotalNumberOfPixels()

for pixelId in range(numberOfPixels):
  aimHelper.calcPixelCentrePositionForMasking(pixelId)

  pixelCentreX = aimHelper.getPixelCentrePosition(0) 
  pixelCentreY = aimHelper.getPixelCentrePosition(1) -207.94792 #-214.975 #Larmor vertical offset
  pixelCentreZ = aimHelper.getPixelCentrePosition(2) + 25.61 *1000 #Larmor SSD (source to sample distance)

  pixelFile.write( str(pixelId) + '\t' + str(pixelCentreX/1000) + '\t' + str(pixelCentreY/1000) + '\t' + str(pixelCentreZ/1000) + "\n" )

pixelFile.close()