#!/usr/bin/env python3

# This is a simple python script for launching multiple parallel cluster jobs. 
# The user needs to specify the number of jobs, which correspond to the number
# of cores occupied, the number of events per job, the output directory, the cluster 
# queue and fill a python list with the name of the simulation script and its arguments (see cmdbase).

# The launch command is based on the DMSC utilities of the simulation framework. It also
# has a dependency on the Core package. Remember to source bootstrap.sh before launching it.

from __future__ import print_function
import os,sys
import Core.System as Sys
njobs=5
nevtsperjob=1000
queue='verylong'
outputdir='/mnt/lustre/groups/loki/geant4/WF/quickTest'

cmdbase=['ess_lokisim_simanachain_wf','results','event_gen=mcpl','allow_zero_weight=n','input_file=/mnt/lustre/groups/loki/mcstas/2.2a/config_1_model_14/geantInput_loki_list.p.x.y.z.kx.ky.kz.t.L.U1.mcpl.gz']

for i in range(njobs): # for seeded events
    cmd = cmdbase+['-n%i'%nevtsperjob,'-s%i'%(7999954+483*i)]
    cmd = ['ess_dmscutils_submit',queue,os.path.join(outputdir,'job%04i'%i)]+cmd

    ec = Sys.system(Sys.quote_cmd(cmd))
    if ec!=0:
        print("Problems encountered while submitting job %i out of %i"%(i+1,njobs))
        sys.exit(1)
        
        
