#!/usr/bin/env python3

import G4GeoLoki.GeoBCSBanks as GEO

geo = GEO.create()

#Define particle generation:
# import G4StdGenerators.ProfiledBeamGen as genmodule
# gen = genmodule.create()
# gen.particleName = 'neutron'
# gen.neutron_wavelength_aangstrom = 12.0
# gen.spread_x_mm=390.0
# gen.offset_x_mm=500.0
# gen.spread_y_mm=1200.0
# #gen.offset_y_mm=0.0
# gen.spread_mode='FLATRECT'

# import G4StdGenerators.FlexGen as Gen
# gen = Gen.create()
# gen.particleName = 'neutron'
# gen.neutron_wavelength_aangstrom = 1.8
# gen.momdir_spherical = True
# #gen.fixed_polarangle_deg = 0.0
# #gen.fixed_polarangle_deg = 25.6 # 6.5 # 9.7 # 27.5 # 32.2
# gen.fixed_azimuthalangle_deg = 90.0 + 90.0 #+180.0

import G4StdGenerators.FlexGen as Gen
gen = Gen.create()
gen.particleName = 'neutron'
gen.neutron_wavelength_aangstrom = 5
gen.momdir_spherical = True
gen.randomize_polarangle = True
gen.random_min_polarangle_deg = 0.0
gen.random_max_polarangle_deg = 45 #5.3 # 8.5 
#gen.random_min_polarangle_deg = 30.0
#gen.random_max_polarangle_deg = 33 #5.3 # 8.5 
gen.randomize_azimuthalangle = True
#gen.random_min_azimuthalangle_deg = 28.0
#gen.random_max_azimuthalangle_deg = 32.0
gen.random_min_azimuthalangle_deg = 0.0
gen.random_max_azimuthalangle_deg = 360.0

#Framework setup
import G4Launcher
launcher = G4Launcher(geo,gen)
launcher.setOutput('bcs_mcpl','REDUCED')#Griff output
launcher.go()



#import LOKI.Common
#LOKI.Common.launch(geo)
