#!/bin/bash

ess_loki_larmor_sim -t -lESS_Empty && \
ess_loki_larmor_sim -lESS_Empty |grep '^G4Launcher::Launcher'
if [ ${PIPESTATUS[0]} == 0 ]; then
    ess_loki_larmor_ana larmor.griff
else
    exit 1
fi
